# TensorFlow Ranking, the project to build ranking models on TensorFlow.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

py_library(
    name = "tensorflow_ranking",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
    deps = [
        "//tensorflow_ranking/python",
        "//tensorflow_ranking/python:version",
    ],
)
