# Docs

# Placeholder: load py_binary

licenses(["notice"])

py_binary(
    name = "build_docs",
    srcs = ["build_docs.py"],
    python_version = "PY3",
    srcs_version = "PY2AND3",
    deps = [
        # py/absl:app dep,
        # py/absl/flags dep,
        # Placeholder: proto upb dep
        # py/tensorflow_docs/api_generator:generate_lib dep,
        # py/tensorflow_docs/api_generator:public_api dep,
        # py/tensorflow_models dep,
        "//tensorflow_ranking",
        "//tensorflow_ranking/extension/premade",
    ],
)
