# Implementation for TF-Ranking lower-level functionalities that can be shared
# by tf.estimator and tf.keras.

package(
    default_visibility = [
        "//tensorflow_ranking:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])
